#!/bin/sh

set -e

./log Installing APT configuration
cp -r overlay/etc/apt /etc

./log Updating package lists
apt-get -qq update

./log Upgrading packages
apt-get -qq upgrade

./package zsh
./package mosh
./package nginx
./package screen
./package php5-gd
./package php5-fpm
./package php5-mysql
./package mysql-server

./log Copying overlay to root filesystem
cp -r overlay/* /

./log Bringing up the HE IPv6 tunnel
ifup he-ipv6

./log Stopping nginx
/etc/init.d/nginx stop

./log Extracting DokuWiki
tar xf extra/dokuwiki-2013-12-08.tgz -C /var/www/wiki.comssa.org.au
mv /var/www/wiki.comssa.org.au/*/* /var/www/wiki.comssa.org.au
rm -r /var/www/wiki.comssa.org.au/dokuwiki-2013-12-08

./log Extracting Kusaba X
unzip kusabax_0.9.3_full.zip -d /var/www/chan.comssa.org.au

./log Fixing permissions for /var/www
chown -R www-data:www-data /var/www
chmod -R 6770 /var/www

./log Starting nginx
/etc/init.d/nginx start

./log Adding user group: comssa
groupadd comssa

./log Adding user group: committee
groupadd committee

./log Limit nproc to 100 for all users except root
echo '* hard nproc 100' > /etc/security/limits.conf

./log Allowing members of commitee to sudo without password
echo '%committee ALL = NOPASSWD: ALL' > /etc/sudoers.d/committee

./log Setting root shell to /bin/false to discourage shell usage
chsh -s /bin/false < /dev/null

./log Disabling root password to prevent password-based login
passwd -l root

./log Deleting authorized_keys to prevent root SSH usage
rm ~/.ssh/authorized_keys

./committee delan
./committee kye

./log Rebooting server, as setup is complete
reboot
